### ISSUE TITLE
unconsistent impact on omnibox

### ISSUE THREAD

**Issue by actino2** [jimschubert/NewTab-Redirect#129] opened 2016-09-10 21:34 UTC
NewTab-Redirect is a great work-around to get the separate Search Box to work again on Chrome and avoid our cursor to automatically jump to the address bar each time we type something in the search box (which drives many of us crazy).

Setting google.com as the default new tab page in NewTab-Redirect allows that to work just fine.  What puzzles me is that it does not always work... I have created 3 different Chrome users (same browser and NewTab-Redirect settings for each), if it works fine on the two first users, NewTab-Redirect has strangely no effect whatsoever on the search box of the third user where search works just the Chrome default way as an omni search.

Any idea why setting google.com on NewTab-Redirect sometimes overides the omni search and get the separate search box to work again, sometimes not?

**Comment by dbkaplun** [comment] 2016-09-17 18:27
In case you haven't solved this already, there's an `iframe` branch which leaves the omnibox empty and doesn't touch the cursor: https://github.com/dbkaplun/NewTab-Redirect/tree/iframe works great for me!

**Comment by chromehangover** [comment] 2016-10-28 23:43
Same issue here. Though I use the exactly same settings  for each google user I create, New Tab Redirect sometimes solve the url/omnibar issue (then allowing to type inside the search box), sometimes not (then keeps jumping to the url/omnibar whenever you type in the search box).

I've spent hours trying to figure out the reason for that change of behavior, without any success.
Anyone has any idea of how can this unconsistent behavior be explained?

sorry dbkaplun, but I don't get a clue of how what you suggest does work.

**Comment by dbkaplun** [comment] 2016-10-28 23:49
```sh
git clone -b iframe git@github.com:dbkaplun/NewTab-Redirect.git
```
Then go to `chrome://extensions/`, click "Load unpacked extension...", and select the newly-created NewTab-Redirect folder you just cloned. Please note that you will have to disable the official NewTab-Redirect in order to use your local copy.

**Comment by jimschubert** [comment] 2016-10-29 00:29
@dbkaplun if you tag a release, you can point users directly to a zip of your repo.

I'm leaving this and all other related issues open, because it's answered so many times in this repository, as well as why I won't implement an iframe solution.

Thanks for pointing people to your solution.

**Comment by jimschubert** [comment] 2017-09-10 16:04
I'm going to close this as a duplicate of #50, and because there's been a provided alternative.

**Closed by jimschubert** 2017-09-10 16:04 UTC
Labels: extensions can't highlight the address bar
