### ISSUE TITLE
Redirects when recovering session

### ISSUE THREAD

**Issue by JZL003** [jimschubert/NewTab-Redirect#102] opened 2015-03-15 22:30 UTC
There might be no way to do this but my computer has a bad habit of shutting down randomly. When that happens, on reopening google chrome a restore button shows up (https://support.google.com/chrome/answer/95268?hl=en)

This extension is great in every other way except that it reloads that page (which to be fair is the new tab page, just with that little recover popup) so I lose my session. Is there a way to disable the redirection when the recover screen popup is open

For clarification, the popup looks like [this](http://forums.techguy.org/attachments/229901d1390944870/chromerestoreerror.png)

**Comment by jimschubert** [comment] 2015-03-16 11:31
To restore your last session in this case, try CTRL+SHIFT+T. Other than that, there's not really a way that I know of to detect the restore and skip the redirect. Please refer to answers in the issue linked below if you have further questions, but feel free to continue commenting on this thread.  

Also, if your machine keeps shutting down you may want to have the power supply, RAM, and CPU checked. I had a similar issue with a desktop computer when I lived in an old apartment... the outlet's wiring was bad and kept killing power supplies.

Closing as a duplicate of previous issues: #100, #93, #78, #66, #44, #8.

**Closed by jimschubert** 2015-03-16 11:31 UTC
