### ISSUE TITLE
Cannot recover browser session after a Google Chrome crash

### ISSUE THREAD

**Issue by charles-esterbrook** [jimschubert/NewTab-Redirect#93] opened 2015-01-24 18:24 UTC
If Chrome crashes (or your machine crashed) then when you start Chrome again, it will prompt you:

Google Chrome didn't shut down correctly. To reopen the pages you had open, click Restore.

This prompt is in a yellow bar at the top of the browser window (but under the window controls like address bar and bookmarks bar). Before I could click on it, TabRedirect kicked in and redirected the tab to a local file (just like its configured) causing the "restore" prompt to disappear. I lost all my tabs.

Also, Chrome doesn't seem to offer another way to invoke that function such as through a menu item.

Reference:
https://support.google.com/chrome/answer/95268?hl=en

So my request is to address them in some way which could include at least any of the following:
* Don't redirect if Chrome didn't start cleanly
* Don't redirect if Chrome shows any kind of dialog/message
* Restore the "restore prompt" after the redirect
* Document a way to invoke Chrome's "Restore" by some other means
* Convince Google to support a "new tab url setting" as part of Chrome  :-)

**Comment by Walkman100** [comment] 2015-01-24 21:32
And I can confirm it is because of the redirect, since my chrome has crashed many times, and I have always been able to click the `Restore` button since I use the default NTR page

**Comment by jimschubert** [comment] 2015-01-24 21:43
This is a known bug in Chrome.

https://code.google.com/p/chromium/issues/detail?id=9890&can=5&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

https://code.google.com/p/chromium/issues/detail?id=406355&can=5&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

There are numerous issues with Chrome's implementation of the New Tab API.  Unfortunately, extensions have no way that I have found to resolve the problem. It exists with every new tab replacement that I've tried.

**Comment by charles-esterbrook** [comment] 2015-01-24 22:03
Thanks for the comments. Btw I was saved by another extension called "The Great Suspender" which eventually showed me all the windows I had before with an option to restore each. What was amazing is that I had restarted Chrome a few times before this came up, but it still remembered.

Btw, I love TabRedirect. Can't believe Chrome doesn't support such a basic feature out of the box. Thanks.

**Comment by jimschubert** [comment] 2015-01-24 22:06
Thanks, I will check out that extension. I had considered adding some tab
tracking to account for the bug, but users generally hate when extensions
record browsing activity (even if it isn't malicious).

**Comment by charles-esterbrook** [comment] 2015-01-24 22:22
You could make it option and leave it off by default. On the other hand, it
looks like I have what I need through the other extension, so it's all good.

**Comment by jimschubert** [comment] 2015-01-25 02:12
Cool, then I'll close this issue. Thanks!

**Closed by jimschubert** 2015-01-25 02:12 UTC

**Comment by Walkman100** [comment] 2015-02-05 16:38
Could this flag: `chrome://flags/#enable-session-crashed-bubble` help at all?

**Comment by jimschubert** [comment] 2015-02-05 16:42
That may work. I'll have to play around with it. I don't know when that
flag was added. Mine is set to 'default', but it doesn't tell me what the
default is :\

On Thu, Feb 5, 2015 at 11:39 AM, ░▒▓█│【Walkman】│█▓▒░ <
notifications@github.com> wrote:

> Could this flag: chrome://flags/#enable-session-crashed-bubble help at
> all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jimschubert/NewTab-Redirect/issues/93#issuecomment-73078804>
> .
>



-- 

________________________
james.schubert@gmail.com
H (804) 571-1924
C (804) 921-7331

**Comment by Walkman100** [comment] 2015-02-05 19:14
From the flags page:
```
Enable session restore bubble UI. [Windows, Linux]
If enabled, the session restore UI will be shown in a bubble instead of an info bar.
```
So I'm guessing If you see it as an info bar, and have it set to `default`, then the default is `disabled`.
I saw it while working through the flags page on a new linux install :D (flag settings don't seem to be synced...)

**Comment by jimschubert** [comment] 2015-02-08 19:56
Weird, last time I encountered a session restore, it showed and hid quickly. On Friday, I took a snapshot of my Windows 8.1 VM and tried the Windows 10 Technical Preview. It was really laggy in Virtual Box so I reverted to the Windows 8.1 snapshot.  The Chrome session restore displayed correctly:

![restore](https://cloud.githubusercontent.com/assets/109659/6098107/3690b474-af89-11e4-90a6-0d9420481c50.PNG)

This is Windows 8.1, Google Chrome 40.0.2214.111 (Official Build) m.

I don't know if this is some sporadic issue or if it's resolved.

**Comment by charles-esterbrook** [comment] 2015-02-08 20:05
Your address bar is blank. Mine has the URL that I redirect to (file:///...). Is yours always blank or just during the restore.

**Comment by jimschubert** [comment] 2015-02-08 20:25
Mine is blank because I use the built in redirect. When you specify a URL, it immediately redirects or updated the tab. I will play around with it a bit more and see if there's a way to figure out the error.

**Comment by Walkman100** [comment] 2015-02-08 21:26
Pretty sure it goes away because of the redirect, and I think that's expected behaviour (since if you type something in the url bar and navigate, it should go away, so if an extension navigates away from the NTP, it will dissapear too). What I want to know is what the flag that enables a 'bubble UI' does.

**Comment by charles-esterbrook** [comment] 2015-02-08 22:04
Walkman100, I agree with you. So then I have questions like: Can the restore prompt be resurrected by the extension? If not, can the restore action be triggered by the action? If not, can we get Chrome changed in some manner to eliminate the conflict?

Re: the bubble, it doesn't work on OS X so it's not interesting to me at this point.

**Comment by infotainor254** [comment] 2017-04-24 12:22
@charles-esterbrook the great suspender is a life saver thanks for helping! @
