### ISSUE TITLE
Empty Address Bar Mimicking a Newtab [Feature Request]

### ISSUE THREAD

**Issue by e-l-y-c-k-ir** [jimschubert/NewTab-Redirect#141] opened 2017-09-10 14:56 UTC
Rather than opening a new tab and having to delete the specified redirected link address everytime it's necessary, is there a way to open to the redirected page but have the address bar defaulted to blank?

**Comment by jimschubert** [comment] 2017-09-10 16:01
Closing as a duplicate of #50, which is not functionality that can be controlled by extension developers.

**Closed by jimschubert** 2017-09-10 16:01 UTC

**Comment by e-l-y-c-k-ir** [comment] 2017-09-10 21:44
Is there a way to apply themes from this site and its extension "https://userstyles.org"
to a Newtab overriding extension?

**Comment by jimschubert** [comment] 2017-09-10 22:26
@e-l-y-c-k-ir I doubt it. Chrome didn't even allow access to Chrome themes from extensions, for security reasons (supposedly).

I'm not familiar with installing extensions from outside of the Chrome Store, although I know it's supported. You'll want to look at the Chrome Extension developer docs.
