### ISSUE TITLE
Unable to Restore Session After Chrome Crashes

### ISSUE THREAD

**Issue by spgurley** [jimschubert/NewTab-Redirect#100] opened 2015-03-11 23:37 UTC
If Chrome crashes, when it's started back up it shows the "Restore" button for a second before the tab gets redirected, but then goes away after the redirect and won't come back even if the browser's back button is pressed. It can be fixed by disabling the New Tab Redirect addon, but since crashes are unpredictable, the only solution would be to keep it disable 24/7, which would defeat the point of even using it.  I know someone will say "just use Ctrl+T to reopen them", but this isn't a solution; since it doesn't restore the session, it just reopens windows one at a time, and doesn't restore them to their original size or position.

**Comment by jimschubert** [comment] 2015-03-12 00:05
Hi, thanks for submitting an issue for this.

While CTRL+T only opens one tab at a time, CTRL+SHIFT+T will open your previous session. I don't know of any tab count or previous number of sessions limit, but I've had it open up to two previous sessions with 20+ tabs each.

There's not really much I can do about this considering the extension replaces the new tab page and it's job is to redirect to a user's specified URL. Google doesn't provide any APIs that allow extensions to interact with the 'Restore' button. There *is* an option in `chrome://flags` to use a bubble instead of an info bar, which may make more sense and be resilient to the redirect. In my opinion, the browser shouldn't display the new tab page when it crashes; it should display a page explaining what happened.

Closing as a duplicate of previous issues: #93, #78, #66, #44, #8.

**Closed by jimschubert** 2015-03-12 00:05 UTC
